### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by matheo** [sanderblue/solar-system-threejs#28]
Hi @sanderblue
Great stuff you got here!

I don't see a LICENSE file or a specific one in the package-json
I'm planning to play with Angular and Three.js simulating the Solar System and this is a great resource. Could you clarify it please?

Thanks a ton!

**Comment by sanderblue** [comment]
Hi there! Thanks for the kind words. I'll add a license now to allow others to use this source code.

**Comment by sanderblue** [comment]
@matheo I added the [Apache License 2.0](https://choosealicense.com/licenses/apache-2.0/) 🙂 Happy coding!

**Comment by matheo** [comment]
Great! thank you very much @sanderblue
